
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Leprechaun tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.CodeDom.Compiler;
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;
using Sitecore.Foundation.ORM.Models;

namespace Sitecore.Feature.PageContent.Models
{
    /// <summary>
	/// IHeroBanner interface generated based on sitecore item
	/// <para>Path: /sitecore/templates/Feature/PageContent/_HeroBanner</para>	
	/// <para>ID: 426756ac-ad69-4111-bfb9-1c376826df32</para>	
	/// </summary>
	[SitecoreType(TemplateId = IHeroBannerConstants.TemplateIdString)]
	[GeneratedCode("Leprechaun", "2.0.0.0")]
	public partial interface IHeroBanner : IGlassBase
	{
		/// <summary>
		/// Represents CTA field
		/// <para>Field Type: General Link</para>	
		/// <para>ID: 4182c34c-f0c4-4407-ad4b-03dcd992a5ad</para>	
        /// <para>Section: Banner</para>
		/// </summary>
        [SitecoreField(FieldName = IHeroBannerConstants.Cta_FieldName)]
        Link Cta { get; set; }/// <summary>
		/// Represents Summary field
		/// <para>Field Type: Multi-Line Text</para>	
		/// <para>ID: cc7f2327-2297-43e4-9859-9f643dad125a</para>	
        /// <para>Section: Banner</para>
		/// </summary>
        [SitecoreField(FieldName = IHeroBannerConstants.Summary_FieldName)]
        string Summary { get; set; }/// <summary>
		/// Represents Title field
		/// <para>Field Type: Single-Line Text</para>	
		/// <para>ID: 4ce0eeb2-7177-4459-ba10-3b05e046c176</para>	
        /// <para>Section: Banner</para>
		/// </summary>
        [SitecoreField(FieldName = IHeroBannerConstants.Title_FieldName)]
        string Title { get; set; }
	}
	
	public static partial class IHeroBannerConstants
	{
		public const string TemplateIdString = "426756ac-ad69-4111-bfb9-1c376826df32";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "HeroBanner";
		
        public static readonly ID Cta_FieldId = new ID("4182c34c-f0c4-4407-ad4b-03dcd992a5ad");
        public const string Cta_FieldName = "CTA";
        public static readonly ID Summary_FieldId = new ID("cc7f2327-2297-43e4-9859-9f643dad125a");
        public const string Summary_FieldName = "Summary";
        public static readonly ID Title_FieldId = new ID("4ce0eeb2-7177-4459-ba10-3b05e046c176");
        public const string Title_FieldName = "Title";
	}
	
	/// <summary>
	/// HeroBanner class generated based on sitecore item	
	/// <para>Path: /sitecore/templates/Feature/PageContent/_HeroBanner</para>	
	/// <para>ID: 426756ac-ad69-4111-bfb9-1c376826df32</para>	
	/// </summary>
	public partial class HeroBanner : GlassBase, IHeroBanner
	{
        /// <summary>
		/// Represents CTA field
		/// <para>Path: /sitecore/templates/Feature/PageContent/_HeroBanner/Banner/CTA</para>	
		/// <para>ID: 4182c34c-f0c4-4407-ad4b-03dcd992a5ad</para>	
		/// </summary>
        [SitecoreField(FieldName = IHeroBannerConstants.Cta_FieldName)]
        public virtual Link Cta { get; set; }/// <summary>
		/// Represents Summary field
		/// <para>Path: /sitecore/templates/Feature/PageContent/_HeroBanner/Banner/Summary</para>	
		/// <para>ID: cc7f2327-2297-43e4-9859-9f643dad125a</para>	
		/// </summary>
        [SitecoreField(FieldName = IHeroBannerConstants.Summary_FieldName)]
        public virtual string Summary { get; set; }/// <summary>
		/// Represents Title field
		/// <para>Path: /sitecore/templates/Feature/PageContent/_HeroBanner/Banner/Title</para>	
		/// <para>ID: 4ce0eeb2-7177-4459-ba10-3b05e046c176</para>	
		/// </summary>
        [SitecoreField(FieldName = IHeroBannerConstants.Title_FieldName)]
        public virtual string Title { get; set; }
	}

    /// <summary>
	/// ITitleTextComponent interface generated based on sitecore item
	/// <para>Path: /sitecore/templates/Feature/PageContent/_TitleTextComponent</para>	
	/// <para>ID: 00ff20f7-2fd4-4824-9355-8d71e84ca03f</para>	
	/// </summary>
	[SitecoreType(TemplateId = ITitleTextComponentConstants.TemplateIdString)]
	[GeneratedCode("Leprechaun", "2.0.0.0")]
	public partial interface ITitleTextComponent : IGlassBase
	{
		/// <summary>
		/// Represents Text field
		/// <para>Field Type: Rich Text</para>	
		/// <para>ID: 0e3b4dcf-875c-4497-b71f-23989a7fad7d</para>	
        /// <para>Section: Title and Text</para>
		/// </summary>
        [SitecoreField(FieldName = ITitleTextComponentConstants.Text_FieldName)]
        string Text { get; set; }/// <summary>
		/// Represents Title field
		/// <para>Field Type: Single-Line Text</para>	
		/// <para>ID: 9abe4302-6a56-4d94-b0f4-15488f765b4a</para>	
        /// <para>Section: Title and Text</para>
		/// </summary>
        [SitecoreField(FieldName = ITitleTextComponentConstants.Title_FieldName)]
        string Title { get; set; }
	}
	
	public static partial class ITitleTextComponentConstants
	{
		public const string TemplateIdString = "00ff20f7-2fd4-4824-9355-8d71e84ca03f";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "TitleTextComponent";
		
        public static readonly ID Text_FieldId = new ID("0e3b4dcf-875c-4497-b71f-23989a7fad7d");
        public const string Text_FieldName = "Text";
        public static readonly ID Title_FieldId = new ID("9abe4302-6a56-4d94-b0f4-15488f765b4a");
        public const string Title_FieldName = "Title";
	}
	
	/// <summary>
	/// TitleTextComponent class generated based on sitecore item	
	/// <para>Path: /sitecore/templates/Feature/PageContent/_TitleTextComponent</para>	
	/// <para>ID: 00ff20f7-2fd4-4824-9355-8d71e84ca03f</para>	
	/// </summary>
	public partial class TitleTextComponent : GlassBase, ITitleTextComponent
	{
        /// <summary>
		/// Represents Text field
		/// <para>Path: /sitecore/templates/Feature/PageContent/_TitleTextComponent/Title and Text/Text</para>	
		/// <para>ID: 0e3b4dcf-875c-4497-b71f-23989a7fad7d</para>	
		/// </summary>
        [SitecoreField(FieldName = ITitleTextComponentConstants.Text_FieldName)]
        public virtual string Text { get; set; }/// <summary>
		/// Represents Title field
		/// <para>Path: /sitecore/templates/Feature/PageContent/_TitleTextComponent/Title and Text/Title</para>	
		/// <para>ID: 9abe4302-6a56-4d94-b0f4-15488f765b4a</para>	
		/// </summary>
        [SitecoreField(FieldName = ITitleTextComponentConstants.Title_FieldName)]
        public virtual string Title { get; set; }
	}

}
