
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Leprechaun tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.CodeDom.Compiler;
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;
using Sitecore.Foundation.ORM.Models;

namespace Sitecore.Feature.Navigation.Models
{
    /// <summary>
	/// IFooter interface generated based on sitecore item
	/// <para>Path: /sitecore/templates/Feature/Navigation/_Footer</para>	
	/// <para>ID: 11a7dad2-e3c3-4aca-a153-83fa9945591a</para>	
	/// </summary>
	[SitecoreType(TemplateId = IFooterConstants.TemplateIdString)]
	[GeneratedCode("Leprechaun", "2.0.0.0")]
	public partial interface IFooter : IGlassBase
	{
		/// <summary>
		/// Represents Copyright field
		/// <para>Field Type: Rich Text</para>	
		/// <para>ID: a5903a32-7404-4ad6-ad1d-88272aada003</para>	
        /// <para>Section: Footer</para>
		/// </summary>
        [SitecoreField(IFooterConstants.Copyright_FieldId, SitecoreFieldType.RichText, "Footer")]
        string Copyright { get; set; }/// <summary>
		/// Represents PageLinks field
		/// <para>Field Type: Treelist</para>	
		/// <para>ID: 67bddcf2-d9d8-4f9e-b518-41f9daf392c9</para>	
        /// <para>Section: Footer</para>
		/// </summary>
        [SitecoreField(IFooterConstants.PageLinks_FieldId, SitecoreFieldType.Treelist, "Footer")]
        IEnumerable<Guid> PageLinks { get; set; }/// <summary>
		/// Represents SocialIcons field
		/// <para>Field Type: Treelist</para>	
		/// <para>ID: c321ceee-b313-4bc3-a98a-a64c7752b40b</para>	
        /// <para>Section: Footer</para>
		/// </summary>
        [SitecoreField(IFooterConstants.SocialIcons_FieldId, SitecoreFieldType.Treelist, "Footer")]
        IEnumerable<Guid> SocialIcons { get; set; }
	}
	
	public static partial class IFooterConstants
	{
		public const string TemplateIdString = "11a7dad2-e3c3-4aca-a153-83fa9945591a";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "Footer";
		
        public static readonly ID Copyright = new ID("a5903a32-7404-4ad6-ad1d-88272aada003");
        public const string Copyright_FieldId = "a5903a32-7404-4ad6-ad1d-88272aada003";
        public const string Copyright_FieldName = "Copyright";
        public static readonly ID PageLinks = new ID("67bddcf2-d9d8-4f9e-b518-41f9daf392c9");
        public const string PageLinks_FieldId = "67bddcf2-d9d8-4f9e-b518-41f9daf392c9";
        public const string PageLinks_FieldName = "PageLinks";
        public static readonly ID SocialIcons = new ID("c321ceee-b313-4bc3-a98a-a64c7752b40b");
        public const string SocialIcons_FieldId = "c321ceee-b313-4bc3-a98a-a64c7752b40b";
        public const string SocialIcons_FieldName = "SocialIcons";
	}
	
	/// <summary>
	/// Footer class generated based on sitecore item	
	/// <para>Path: /sitecore/templates/Feature/Navigation/_Footer</para>	
	/// <para>ID: 11a7dad2-e3c3-4aca-a153-83fa9945591a</para>	
	/// </summary>
	public partial class Footer : GlassBase, IFooter
	{
        /// <summary>
		/// Represents Copyright field
		/// <para>Path: /sitecore/templates/Feature/Navigation/_Footer/Footer/Copyright</para>	
		/// <para>ID: a5903a32-7404-4ad6-ad1d-88272aada003</para>	
		/// </summary>
        [SitecoreField(IFooterConstants.Copyright_FieldId, SitecoreFieldType.RichText, "Footer")]
        public virtual string Copyright { get; set; }/// <summary>
		/// Represents PageLinks field
		/// <para>Path: /sitecore/templates/Feature/Navigation/_Footer/Footer/PageLinks</para>	
		/// <para>ID: 67bddcf2-d9d8-4f9e-b518-41f9daf392c9</para>	
		/// </summary>
        [SitecoreField(IFooterConstants.PageLinks_FieldId, SitecoreFieldType.Treelist, "Footer")]
        public virtual IEnumerable<Guid> PageLinks { get; set; }/// <summary>
		/// Represents SocialIcons field
		/// <para>Path: /sitecore/templates/Feature/Navigation/_Footer/Footer/SocialIcons</para>	
		/// <para>ID: c321ceee-b313-4bc3-a98a-a64c7752b40b</para>	
		/// </summary>
        [SitecoreField(IFooterConstants.SocialIcons_FieldId, SitecoreFieldType.Treelist, "Footer")]
        public virtual IEnumerable<Guid> SocialIcons { get; set; }
	}

    /// <summary>
	/// IHeader interface generated based on sitecore item
	/// <para>Path: /sitecore/templates/Feature/Navigation/_Header</para>	
	/// <para>ID: 375ade51-91eb-4c37-8e39-ade42c58bbbb</para>	
	/// </summary>
	[SitecoreType(TemplateId = IHeaderConstants.TemplateIdString)]
	[GeneratedCode("Leprechaun", "2.0.0.0")]
	public partial interface IHeader : IGlassBase
	{
		/// <summary>
		/// Represents Logo field
		/// <para>Field Type: Image</para>	
		/// <para>ID: 1b0e769a-ff34-4825-b87e-508b6997c264</para>	
        /// <para>Section: Header</para>
		/// </summary>
        [SitecoreField(IHeaderConstants.Logo_FieldId, SitecoreFieldType.Image, "Header")]
        Image Logo { get; set; }/// <summary>
		/// Represents Pages field
		/// <para>Field Type: Treelist</para>	
		/// <para>ID: e4c7532a-3cb3-41ba-9885-a674e3d24d83</para>	
        /// <para>Section: Header</para>
		/// </summary>
        [SitecoreField(IHeaderConstants.Pages_FieldId, SitecoreFieldType.Treelist, "Header")]
        IEnumerable<Guid> Pages { get; set; }
	}
	
	public static partial class IHeaderConstants
	{
		public const string TemplateIdString = "375ade51-91eb-4c37-8e39-ade42c58bbbb";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "Header";
		
        public static readonly ID Logo = new ID("1b0e769a-ff34-4825-b87e-508b6997c264");
        public const string Logo_FieldId = "1b0e769a-ff34-4825-b87e-508b6997c264";
        public const string Logo_FieldName = "Logo";
        public static readonly ID Pages = new ID("e4c7532a-3cb3-41ba-9885-a674e3d24d83");
        public const string Pages_FieldId = "e4c7532a-3cb3-41ba-9885-a674e3d24d83";
        public const string Pages_FieldName = "Pages";
	}
	
	/// <summary>
	/// Header class generated based on sitecore item	
	/// <para>Path: /sitecore/templates/Feature/Navigation/_Header</para>	
	/// <para>ID: 375ade51-91eb-4c37-8e39-ade42c58bbbb</para>	
	/// </summary>
	public partial class Header : GlassBase, IHeader
	{
        /// <summary>
		/// Represents Logo field
		/// <para>Path: /sitecore/templates/Feature/Navigation/_Header/Header/Logo</para>	
		/// <para>ID: 1b0e769a-ff34-4825-b87e-508b6997c264</para>	
		/// </summary>
        [SitecoreField(IHeaderConstants.Logo_FieldId, SitecoreFieldType.Image, "Header")]
        public virtual Image Logo { get; set; }/// <summary>
		/// Represents Pages field
		/// <para>Path: /sitecore/templates/Feature/Navigation/_Header/Header/Pages</para>	
		/// <para>ID: e4c7532a-3cb3-41ba-9885-a674e3d24d83</para>	
		/// </summary>
        [SitecoreField(IHeaderConstants.Pages_FieldId, SitecoreFieldType.Treelist, "Header")]
        public virtual IEnumerable<Guid> Pages { get; set; }
	}

    /// <summary>
	/// INavigablePage interface generated based on sitecore item
	/// <para>Path: /sitecore/templates/Feature/Navigation/_NavigablePage</para>	
	/// <para>ID: 42e2ddc0-58b1-49c2-bf27-a5a3bfb44923</para>	
	/// </summary>
	[SitecoreType(TemplateId = INavigablePageConstants.TemplateIdString)]
	[GeneratedCode("Leprechaun", "2.0.0.0")]
	public partial interface INavigablePage : IGlassBase
	{
		/// <summary>
		/// Represents Navigation Title field
		/// <para>Field Type: Single-Line Text</para>	
		/// <para>ID: e87fbd04-1210-4739-952a-25685ba15938</para>	
        /// <para>Section: Navigation</para>
		/// </summary>
        [SitecoreField(INavigablePageConstants.NavigationTitle_FieldId, SitecoreFieldType.SingleLineText, "Navigation")]
        string NavigationTitle { get; set; }/// <summary>
		/// Represents ShowInNavigation field
		/// <para>Field Type: Checkbox</para>	
		/// <para>ID: 10557651-153d-4334-8583-fb35b5f30023</para>	
        /// <para>Section: Navigation</para>
		/// </summary>
        [SitecoreField(INavigablePageConstants.ShowInNavigation_FieldId, SitecoreFieldType.Checkbox, "Navigation")]
        bool ShowInNavigation { get; set; }/// <summary>
		/// Represents Summary field
		/// <para>Field Type: Multi-Line Text</para>	
		/// <para>ID: b74bf1f6-9c48-4e02-9f39-7a2460dbd0fe</para>	
        /// <para>Section: Navigation</para>
		/// </summary>
        [SitecoreField(INavigablePageConstants.Summary_FieldId, SitecoreFieldType.MultiLineText, "Navigation")]
        string Summary { get; set; }
	}
	
	public static partial class INavigablePageConstants
	{
		public const string TemplateIdString = "42e2ddc0-58b1-49c2-bf27-a5a3bfb44923";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "NavigablePage";
		
        public static readonly ID NavigationTitle = new ID("e87fbd04-1210-4739-952a-25685ba15938");
        public const string NavigationTitle_FieldId = "e87fbd04-1210-4739-952a-25685ba15938";
        public const string NavigationTitle_FieldName = "Navigation Title";
        public static readonly ID ShowInNavigation = new ID("10557651-153d-4334-8583-fb35b5f30023");
        public const string ShowInNavigation_FieldId = "10557651-153d-4334-8583-fb35b5f30023";
        public const string ShowInNavigation_FieldName = "ShowInNavigation";
        public static readonly ID Summary = new ID("b74bf1f6-9c48-4e02-9f39-7a2460dbd0fe");
        public const string Summary_FieldId = "b74bf1f6-9c48-4e02-9f39-7a2460dbd0fe";
        public const string Summary_FieldName = "Summary";
	}
	
	/// <summary>
	/// NavigablePage class generated based on sitecore item	
	/// <para>Path: /sitecore/templates/Feature/Navigation/_NavigablePage</para>	
	/// <para>ID: 42e2ddc0-58b1-49c2-bf27-a5a3bfb44923</para>	
	/// </summary>
	public partial class NavigablePage : GlassBase, INavigablePage
	{
        /// <summary>
		/// Represents Navigation Title field
		/// <para>Path: /sitecore/templates/Feature/Navigation/_NavigablePage/Navigation/Navigation Title</para>	
		/// <para>ID: e87fbd04-1210-4739-952a-25685ba15938</para>	
		/// </summary>
        [SitecoreField(INavigablePageConstants.NavigationTitle_FieldId, SitecoreFieldType.SingleLineText, "Navigation")]
        public virtual string NavigationTitle { get; set; }/// <summary>
		/// Represents ShowInNavigation field
		/// <para>Path: /sitecore/templates/Feature/Navigation/_NavigablePage/Navigation/ShowInNavigation</para>	
		/// <para>ID: 10557651-153d-4334-8583-fb35b5f30023</para>	
		/// </summary>
        [SitecoreField(INavigablePageConstants.ShowInNavigation_FieldId, SitecoreFieldType.Checkbox, "Navigation")]
        public virtual bool ShowInNavigation { get; set; }/// <summary>
		/// Represents Summary field
		/// <para>Path: /sitecore/templates/Feature/Navigation/_NavigablePage/Navigation/Summary</para>	
		/// <para>ID: b74bf1f6-9c48-4e02-9f39-7a2460dbd0fe</para>	
		/// </summary>
        [SitecoreField(INavigablePageConstants.Summary_FieldId, SitecoreFieldType.MultiLineText, "Navigation")]
        public virtual string Summary { get; set; }
	}

}
