
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Leprechaun tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.CodeDom.Compiler;
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;
using Sitecore.Foundation.ORM.Models;

namespace Sitecore.Project.Test.Models.PageType
{
    /// <summary>
	/// IGeneralPage interface generated based on sitecore item
	/// <para>Path: /sitecore/templates/Project/Test/Page Type/GeneralPage</para>	
	/// <para>ID: 81a02a6d-349e-4cc4-b12b-3eb85e09cce4</para>	
	/// </summary>
	[SitecoreType(TemplateId = IGeneralPageConstants.TemplateIdString)]
	[GeneratedCode("Leprechaun", "2.0.0.0")]
	public partial interface IGeneralPage : IGlassBase
	{
		
	}
	
	public static partial class IGeneralPageConstants
	{
		public const string TemplateIdString = "81a02a6d-349e-4cc4-b12b-3eb85e09cce4";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "GeneralPage";
		
	}
	
	/// <summary>
	/// GeneralPage class generated based on sitecore item	
	/// <para>Path: /sitecore/templates/Project/Test/Page Type/GeneralPage</para>	
	/// <para>ID: 81a02a6d-349e-4cc4-b12b-3eb85e09cce4</para>	
	/// </summary>
	public partial class GeneralPage : GlassBase, IGeneralPage
	{
        
	}

    /// <summary>
	/// IHeroBanner interface generated based on sitecore item
	/// <para>Path: /sitecore/templates/Project/Test/Content Type/Hero Banner</para>	
	/// <para>ID: cd727311-4b70-40e8-93a9-c78a5689ad6c</para>	
	/// </summary>
	[SitecoreType(TemplateId = IHeroBannerConstants.TemplateIdString)]
	[GeneratedCode("Leprechaun", "2.0.0.0")]
	public partial interface IHeroBanner : IGlassBase
	{
		
	}
	
	public static partial class IHeroBannerConstants
	{
		public const string TemplateIdString = "cd727311-4b70-40e8-93a9-c78a5689ad6c";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "HeroBanner";
		
	}
	
	/// <summary>
	/// HeroBanner class generated based on sitecore item	
	/// <para>Path: /sitecore/templates/Project/Test/Content Type/Hero Banner</para>	
	/// <para>ID: cd727311-4b70-40e8-93a9-c78a5689ad6c</para>	
	/// </summary>
	public partial class HeroBanner : GlassBase, IHeroBanner
	{
        
	}

    /// <summary>
	/// IImageComponent interface generated based on sitecore item
	/// <para>Path: /sitecore/templates/Project/Test/Content Type/Image Component</para>	
	/// <para>ID: ee2c6b0e-6303-4beb-a093-117bc8c42853</para>	
	/// </summary>
	[SitecoreType(TemplateId = IImageComponentConstants.TemplateIdString)]
	[GeneratedCode("Leprechaun", "2.0.0.0")]
	public partial interface IImageComponent : IGlassBase
	{
		
	}
	
	public static partial class IImageComponentConstants
	{
		public const string TemplateIdString = "ee2c6b0e-6303-4beb-a093-117bc8c42853";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "ImageComponent";
		
	}
	
	/// <summary>
	/// ImageComponent class generated based on sitecore item	
	/// <para>Path: /sitecore/templates/Project/Test/Content Type/Image Component</para>	
	/// <para>ID: ee2c6b0e-6303-4beb-a093-117bc8c42853</para>	
	/// </summary>
	public partial class ImageComponent : GlassBase, IImageComponent
	{
        
	}

    /// <summary>
	/// ISiteRoot interface generated based on sitecore item
	/// <para>Path: /sitecore/templates/Project/Test/Content Type/SiteRoot</para>	
	/// <para>ID: dd4bfa87-d9d5-4627-8a95-bffd5a32846e</para>	
	/// </summary>
	[SitecoreType(TemplateId = ISiteRootConstants.TemplateIdString)]
	[GeneratedCode("Leprechaun", "2.0.0.0")]
	public partial interface ISiteRoot : IGlassBase
	{
		
	}
	
	public static partial class ISiteRootConstants
	{
		public const string TemplateIdString = "dd4bfa87-d9d5-4627-8a95-bffd5a32846e";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "SiteRoot";
		
	}
	
	/// <summary>
	/// SiteRoot class generated based on sitecore item	
	/// <para>Path: /sitecore/templates/Project/Test/Content Type/SiteRoot</para>	
	/// <para>ID: dd4bfa87-d9d5-4627-8a95-bffd5a32846e</para>	
	/// </summary>
	public partial class SiteRoot : GlassBase, ISiteRoot
	{
        
	}

    /// <summary>
	/// ISocialIcon interface generated based on sitecore item
	/// <para>Path: /sitecore/templates/Project/Test/Content Type/SocialIcon</para>	
	/// <para>ID: 68d01aed-bc19-458b-9b48-2198bbb5803a</para>	
	/// </summary>
	[SitecoreType(TemplateId = ISocialIconConstants.TemplateIdString)]
	[GeneratedCode("Leprechaun", "2.0.0.0")]
	public partial interface ISocialIcon : IGlassBase
	{
		
	}
	
	public static partial class ISocialIconConstants
	{
		public const string TemplateIdString = "68d01aed-bc19-458b-9b48-2198bbb5803a";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "SocialIcon";
		
	}
	
	/// <summary>
	/// SocialIcon class generated based on sitecore item	
	/// <para>Path: /sitecore/templates/Project/Test/Content Type/SocialIcon</para>	
	/// <para>ID: 68d01aed-bc19-458b-9b48-2198bbb5803a</para>	
	/// </summary>
	public partial class SocialIcon : GlassBase, ISocialIcon
	{
        
	}

    /// <summary>
	/// ITitleTextComponent interface generated based on sitecore item
	/// <para>Path: /sitecore/templates/Project/Test/Content Type/Title Text Component</para>	
	/// <para>ID: 6d8deed0-1d1c-4472-8281-e788850c94b4</para>	
	/// </summary>
	[SitecoreType(TemplateId = ITitleTextComponentConstants.TemplateIdString)]
	[GeneratedCode("Leprechaun", "2.0.0.0")]
	public partial interface ITitleTextComponent : IGlassBase
	{
		
	}
	
	public static partial class ITitleTextComponentConstants
	{
		public const string TemplateIdString = "6d8deed0-1d1c-4472-8281-e788850c94b4";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "TitleTextComponent";
		
	}
	
	/// <summary>
	/// TitleTextComponent class generated based on sitecore item	
	/// <para>Path: /sitecore/templates/Project/Test/Content Type/Title Text Component</para>	
	/// <para>ID: 6d8deed0-1d1c-4472-8281-e788850c94b4</para>	
	/// </summary>
	public partial class TitleTextComponent : GlassBase, ITitleTextComponent
	{
        
	}

    /// <summary>
	/// IVideoComponent interface generated based on sitecore item
	/// <para>Path: /sitecore/templates/Project/Test/Content Type/Video Component</para>	
	/// <para>ID: 415ebdec-da60-4bb7-ae61-4fd6a3126301</para>	
	/// </summary>
	[SitecoreType(TemplateId = IVideoComponentConstants.TemplateIdString)]
	[GeneratedCode("Leprechaun", "2.0.0.0")]
	public partial interface IVideoComponent : IGlassBase
	{
		
	}
	
	public static partial class IVideoComponentConstants
	{
		public const string TemplateIdString = "415ebdec-da60-4bb7-ae61-4fd6a3126301";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "VideoComponent";
		
	}
	
	/// <summary>
	/// VideoComponent class generated based on sitecore item	
	/// <para>Path: /sitecore/templates/Project/Test/Content Type/Video Component</para>	
	/// <para>ID: 415ebdec-da60-4bb7-ae61-4fd6a3126301</para>	
	/// </summary>
	public partial class VideoComponent : GlassBase, IVideoComponent
	{
        
	}

}
