
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Leprechaun tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.CodeDom.Compiler;
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;
using Sitecore.Foundation.ORM.Models;

namespace Sitecore.Foundation.Design.Models
{
    /// <summary>
	/// IDesignLookupValue interface generated based on sitecore item
	/// <para>Path: /sitecore/templates/Foundation/Design/DesignLookupValue</para>	
	/// <para>ID: 55c3a889-4f39-48eb-8f93-82c98f8a670d</para>	
	/// </summary>
	[SitecoreType(TemplateId = IDesignLookupValueConstants.TemplateIdString)]
	[GeneratedCode("Leprechaun", "2.0.0.0")]
	public partial interface IDesignLookupValue : IGlassBase
	{
		/// <summary>
		/// Represents Value field
		/// <para>Field Type: Single-Line Text</para>	
		/// <para>ID: 95bf480c-79dd-42d6-a290-4d7e1a637945</para>	
        /// <para>Section: Lookup</para>
		/// </summary>
        [SitecoreField(IDesignLookupValueConstants.Value_FieldId, SitecoreFieldType.SingleLineText, "Lookup")]
        string Value { get; set; }
	}
	
	public static partial class IDesignLookupValueConstants
	{
		public const string TemplateIdString = "55c3a889-4f39-48eb-8f93-82c98f8a670d";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "DesignLookupValue";
		
        public static readonly ID Value = new ID("95bf480c-79dd-42d6-a290-4d7e1a637945");
        public const string Value_FieldId = "95bf480c-79dd-42d6-a290-4d7e1a637945";
        public const string Value_FieldName = "Value";
	}
	
	/// <summary>
	/// DesignLookupValue class generated based on sitecore item	
	/// <para>Path: /sitecore/templates/Foundation/Design/DesignLookupValue</para>	
	/// <para>ID: 55c3a889-4f39-48eb-8f93-82c98f8a670d</para>	
	/// </summary>
	public partial class DesignLookupValue : GlassBase, IDesignLookupValue
	{
        /// <summary>
		/// Represents Value field
		/// <para>Path: /sitecore/templates/Foundation/Design/DesignLookupValue/Lookup/Value</para>	
		/// <para>ID: 95bf480c-79dd-42d6-a290-4d7e1a637945</para>	
		/// </summary>
        [SitecoreField(IDesignLookupValueConstants.Value_FieldId, SitecoreFieldType.SingleLineText, "Lookup")]
        public virtual string Value { get; set; }
	}

    /// <summary>
	/// IBackgroundColorBase interface generated based on sitecore item
	/// <para>Path: /sitecore/templates/Foundation/Design/_BackgroundColorBase</para>	
	/// <para>ID: c332a8f2-7576-44bd-a0b4-2a510541b838</para>	
	/// </summary>
	[SitecoreType(TemplateId = IBackgroundColorBaseConstants.TemplateIdString)]
	[GeneratedCode("Leprechaun", "2.0.0.0")]
	public partial interface IBackgroundColorBase : IGlassBase
	{
		/// <summary>
		/// Represents BackgroundColor field
		/// <para>Field Type: Droplink</para>	
		/// <para>ID: ca232b43-2e39-443d-8f1c-41a07e8d1740</para>	
        /// <para>Section: Design</para>
		/// </summary>
        [SitecoreField(IBackgroundColorBaseConstants.BackgroundColor_FieldId, SitecoreFieldType.Droplink, "Design")]
        Guid BackgroundColor { get; set; }
	}
	
	public static partial class IBackgroundColorBaseConstants
	{
		public const string TemplateIdString = "c332a8f2-7576-44bd-a0b4-2a510541b838";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "BackgroundColorBase";
		
        public static readonly ID BackgroundColor = new ID("ca232b43-2e39-443d-8f1c-41a07e8d1740");
        public const string BackgroundColor_FieldId = "ca232b43-2e39-443d-8f1c-41a07e8d1740";
        public const string BackgroundColor_FieldName = "BackgroundColor";
	}
	
	/// <summary>
	/// BackgroundColorBase class generated based on sitecore item	
	/// <para>Path: /sitecore/templates/Foundation/Design/_BackgroundColorBase</para>	
	/// <para>ID: c332a8f2-7576-44bd-a0b4-2a510541b838</para>	
	/// </summary>
	public partial class BackgroundColorBase : GlassBase, IBackgroundColorBase
	{
        /// <summary>
		/// Represents BackgroundColor field
		/// <para>Path: /sitecore/templates/Foundation/Design/_BackgroundColorBase/Design/BackgroundColor</para>	
		/// <para>ID: ca232b43-2e39-443d-8f1c-41a07e8d1740</para>	
		/// </summary>
        [SitecoreField(IBackgroundColorBaseConstants.BackgroundColor_FieldId, SitecoreFieldType.Droplink, "Design")]
        public virtual Guid BackgroundColor { get; set; }
	}

    /// <summary>
	/// ICtabase interface generated based on sitecore item
	/// <para>Path: /sitecore/templates/Foundation/Design/_CTABase</para>	
	/// <para>ID: 6b0e115a-257a-423c-b999-494977912fe3</para>	
	/// </summary>
	[SitecoreType(TemplateId = ICtabaseConstants.TemplateIdString)]
	[GeneratedCode("Leprechaun", "2.0.0.0")]
	public partial interface ICtabase : IGlassBase
	{
		/// <summary>
		/// Represents CTAColor field
		/// <para>Field Type: Droplink</para>	
		/// <para>ID: cba77125-22c5-4c26-a896-141c44a7c93b</para>	
        /// <para>Section: CTA</para>
		/// </summary>
        [SitecoreField(ICtabaseConstants.Ctacolor_FieldId, SitecoreFieldType.Droplink, "CTA")]
        Guid Ctacolor { get; set; }/// <summary>
		/// Represents CTATextColor field
		/// <para>Field Type: Droplink</para>	
		/// <para>ID: a01b69b4-91e5-4678-a8f1-9ec4552e2d80</para>	
        /// <para>Section: CTA</para>
		/// </summary>
        [SitecoreField(ICtabaseConstants.CtatextColor_FieldId, SitecoreFieldType.Droplink, "CTA")]
        Guid CtatextColor { get; set; }
	}
	
	public static partial class ICtabaseConstants
	{
		public const string TemplateIdString = "6b0e115a-257a-423c-b999-494977912fe3";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "Ctabase";
		
        public static readonly ID Ctacolor = new ID("cba77125-22c5-4c26-a896-141c44a7c93b");
        public const string Ctacolor_FieldId = "cba77125-22c5-4c26-a896-141c44a7c93b";
        public const string Ctacolor_FieldName = "CTAColor";
        public static readonly ID CtatextColor = new ID("a01b69b4-91e5-4678-a8f1-9ec4552e2d80");
        public const string CtatextColor_FieldId = "a01b69b4-91e5-4678-a8f1-9ec4552e2d80";
        public const string CtatextColor_FieldName = "CTATextColor";
	}
	
	/// <summary>
	/// Ctabase class generated based on sitecore item	
	/// <para>Path: /sitecore/templates/Foundation/Design/_CTABase</para>	
	/// <para>ID: 6b0e115a-257a-423c-b999-494977912fe3</para>	
	/// </summary>
	public partial class Ctabase : GlassBase, ICtabase
	{
        /// <summary>
		/// Represents CTAColor field
		/// <para>Path: /sitecore/templates/Foundation/Design/_CTABase/CTA/CTAColor</para>	
		/// <para>ID: cba77125-22c5-4c26-a896-141c44a7c93b</para>	
		/// </summary>
        [SitecoreField(ICtabaseConstants.Ctacolor_FieldId, SitecoreFieldType.Droplink, "CTA")]
        public virtual Guid Ctacolor { get; set; }/// <summary>
		/// Represents CTATextColor field
		/// <para>Path: /sitecore/templates/Foundation/Design/_CTABase/CTA/CTATextColor</para>	
		/// <para>ID: a01b69b4-91e5-4678-a8f1-9ec4552e2d80</para>	
		/// </summary>
        [SitecoreField(ICtabaseConstants.CtatextColor_FieldId, SitecoreFieldType.Droplink, "CTA")]
        public virtual Guid CtatextColor { get; set; }
	}

    /// <summary>
	/// ITextAlignmentBase interface generated based on sitecore item
	/// <para>Path: /sitecore/templates/Foundation/Design/_TextAlignmentBase</para>	
	/// <para>ID: 54fbe5de-0ad6-4ac7-84c8-9c3b650c053a</para>	
	/// </summary>
	[SitecoreType(TemplateId = ITextAlignmentBaseConstants.TemplateIdString)]
	[GeneratedCode("Leprechaun", "2.0.0.0")]
	public partial interface ITextAlignmentBase : IGlassBase
	{
		/// <summary>
		/// Represents TextAlignment field
		/// <para>Field Type: Droplink</para>	
		/// <para>ID: da4d8777-a4d7-4eff-a755-05ccf304648b</para>	
        /// <para>Section: Design</para>
		/// </summary>
        [SitecoreField(ITextAlignmentBaseConstants.TextAlignment_FieldId, SitecoreFieldType.Droplink, "Design")]
        Guid TextAlignment { get; set; }
	}
	
	public static partial class ITextAlignmentBaseConstants
	{
		public const string TemplateIdString = "54fbe5de-0ad6-4ac7-84c8-9c3b650c053a";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "TextAlignmentBase";
		
        public static readonly ID TextAlignment = new ID("da4d8777-a4d7-4eff-a755-05ccf304648b");
        public const string TextAlignment_FieldId = "da4d8777-a4d7-4eff-a755-05ccf304648b";
        public const string TextAlignment_FieldName = "TextAlignment";
	}
	
	/// <summary>
	/// TextAlignmentBase class generated based on sitecore item	
	/// <para>Path: /sitecore/templates/Foundation/Design/_TextAlignmentBase</para>	
	/// <para>ID: 54fbe5de-0ad6-4ac7-84c8-9c3b650c053a</para>	
	/// </summary>
	public partial class TextAlignmentBase : GlassBase, ITextAlignmentBase
	{
        /// <summary>
		/// Represents TextAlignment field
		/// <para>Path: /sitecore/templates/Foundation/Design/_TextAlignmentBase/Design/TextAlignment</para>	
		/// <para>ID: da4d8777-a4d7-4eff-a755-05ccf304648b</para>	
		/// </summary>
        [SitecoreField(ITextAlignmentBaseConstants.TextAlignment_FieldId, SitecoreFieldType.Droplink, "Design")]
        public virtual Guid TextAlignment { get; set; }
	}

    /// <summary>
	/// ITextColorBase interface generated based on sitecore item
	/// <para>Path: /sitecore/templates/Foundation/Design/_TextColorBase</para>	
	/// <para>ID: e80ddd39-9137-4d3a-993f-f25ff90de4aa</para>	
	/// </summary>
	[SitecoreType(TemplateId = ITextColorBaseConstants.TemplateIdString)]
	[GeneratedCode("Leprechaun", "2.0.0.0")]
	public partial interface ITextColorBase : IGlassBase
	{
		/// <summary>
		/// Represents TextColor field
		/// <para>Field Type: Droplink</para>	
		/// <para>ID: 23cf19eb-e8ca-42a8-92a5-c04959f6bf0b</para>	
        /// <para>Section: Design</para>
		/// </summary>
        [SitecoreField(ITextColorBaseConstants.TextColor_FieldId, SitecoreFieldType.Droplink, "Design")]
        Guid TextColor { get; set; }
	}
	
	public static partial class ITextColorBaseConstants
	{
		public const string TemplateIdString = "e80ddd39-9137-4d3a-993f-f25ff90de4aa";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "TextColorBase";
		
        public static readonly ID TextColor = new ID("23cf19eb-e8ca-42a8-92a5-c04959f6bf0b");
        public const string TextColor_FieldId = "23cf19eb-e8ca-42a8-92a5-c04959f6bf0b";
        public const string TextColor_FieldName = "TextColor";
	}
	
	/// <summary>
	/// TextColorBase class generated based on sitecore item	
	/// <para>Path: /sitecore/templates/Foundation/Design/_TextColorBase</para>	
	/// <para>ID: e80ddd39-9137-4d3a-993f-f25ff90de4aa</para>	
	/// </summary>
	public partial class TextColorBase : GlassBase, ITextColorBase
	{
        /// <summary>
		/// Represents TextColor field
		/// <para>Path: /sitecore/templates/Foundation/Design/_TextColorBase/Design/TextColor</para>	
		/// <para>ID: 23cf19eb-e8ca-42a8-92a5-c04959f6bf0b</para>	
		/// </summary>
        [SitecoreField(ITextColorBaseConstants.TextColor_FieldId, SitecoreFieldType.Droplink, "Design")]
        public virtual Guid TextColor { get; set; }
	}

}
