
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Leprechaun tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.CodeDom.Compiler;
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;
using Sitecore.Foundation.ORM.Models;

namespace Sitecore.Feature.Media.Models
{
    /// <summary>
	/// IImageComponent interface generated based on sitecore item
	/// <para>Path: /sitecore/templates/Feature/Media/_ImageComponent</para>	
	/// <para>ID: 4f5a7fbf-e555-4b85-802e-2075c686b225</para>	
	/// </summary>
	[SitecoreType(TemplateId = IImageComponentConstants.TemplateIdString)]
	[GeneratedCode("Leprechaun", "2.0.0.0")]
	public partial interface IImageComponent : IGlassBase
	{
		/// <summary>
		/// Represents Image field
		/// <para>Field Type: Image</para>	
		/// <para>ID: 22025177-9559-476a-ab5c-c50aa4c8bc45</para>	
        /// <para>Section: Image</para>
		/// </summary>
        [SitecoreField(IImageComponentConstants.Image_FieldId, SitecoreFieldType.Image, "Image")]
        Image Image { get; set; }
	}
	
	public static partial class IImageComponentConstants
	{
		public const string TemplateIdString = "4f5a7fbf-e555-4b85-802e-2075c686b225";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "ImageComponent";
		
        public static readonly ID Image = new ID("22025177-9559-476a-ab5c-c50aa4c8bc45");
        public const string Image_FieldId = "22025177-9559-476a-ab5c-c50aa4c8bc45";
        public const string Image_FieldName = "Image";
	}
	
	/// <summary>
	/// ImageComponent class generated based on sitecore item	
	/// <para>Path: /sitecore/templates/Feature/Media/_ImageComponent</para>	
	/// <para>ID: 4f5a7fbf-e555-4b85-802e-2075c686b225</para>	
	/// </summary>
	public partial class ImageComponent : GlassBase, IImageComponent
	{
        /// <summary>
		/// Represents Image field
		/// <para>Path: /sitecore/templates/Feature/Media/_ImageComponent/Image/Image</para>	
		/// <para>ID: 22025177-9559-476a-ab5c-c50aa4c8bc45</para>	
		/// </summary>
        [SitecoreField(IImageComponentConstants.Image_FieldId, SitecoreFieldType.Image, "Image")]
        public virtual Image Image { get; set; }
	}

    /// <summary>
	/// IVideoComponent interface generated based on sitecore item
	/// <para>Path: /sitecore/templates/Feature/Media/_VideoComponent</para>	
	/// <para>ID: 54875942-29b6-4697-82b1-85df209a29f3</para>	
	/// </summary>
	[SitecoreType(TemplateId = IVideoComponentConstants.TemplateIdString)]
	[GeneratedCode("Leprechaun", "2.0.0.0")]
	public partial interface IVideoComponent : IGlassBase
	{
		/// <summary>
		/// Represents Video Url field
		/// <para>Field Type: Single-Line Text</para>	
		/// <para>ID: 8be40dd8-089e-4c05-8526-99f1d56f24a8</para>	
        /// <para>Section: Video</para>
		/// </summary>
        [SitecoreField(IVideoComponentConstants.VideoUrl_FieldId, SitecoreFieldType.SingleLineText, "Video")]
        string VideoUrl { get; set; }
	}
	
	public static partial class IVideoComponentConstants
	{
		public const string TemplateIdString = "54875942-29b6-4697-82b1-85df209a29f3";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "VideoComponent";
		
        public static readonly ID VideoUrl = new ID("8be40dd8-089e-4c05-8526-99f1d56f24a8");
        public const string VideoUrl_FieldId = "8be40dd8-089e-4c05-8526-99f1d56f24a8";
        public const string VideoUrl_FieldName = "Video Url";
	}
	
	/// <summary>
	/// VideoComponent class generated based on sitecore item	
	/// <para>Path: /sitecore/templates/Feature/Media/_VideoComponent</para>	
	/// <para>ID: 54875942-29b6-4697-82b1-85df209a29f3</para>	
	/// </summary>
	public partial class VideoComponent : GlassBase, IVideoComponent
	{
        /// <summary>
		/// Represents Video Url field
		/// <para>Path: /sitecore/templates/Feature/Media/_VideoComponent/Video/Video Url</para>	
		/// <para>ID: 8be40dd8-089e-4c05-8526-99f1d56f24a8</para>	
		/// </summary>
        [SitecoreField(IVideoComponentConstants.VideoUrl_FieldId, SitecoreFieldType.SingleLineText, "Video")]
        public virtual string VideoUrl { get; set; }
	}

}
